# Generated by Django 2.2.4 on 2019-10-26 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191026_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
        migrations.AlterField(
            model_name='community',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
